using Microsoft.AspNetCore.Mvc;

namespace SFR_Frontend.Server.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class CitiesController : ControllerBase
    {
        private readonly List<string> cities = new();

        private readonly ILogger<CitiesController> _logger;

        public CitiesController(ILogger<CitiesController> logger)
        {
            _logger = logger;

            cities.Add("Andau");
            cities.Add("Antau");
            cities.Add("Apetlon");
            cities.Add("Bad Sauerbrunn");
            cities.Add("Bad Tatzmannsdorf");
            cities.Add("Badersdorf");
            cities.Add("Baumgarten");
            cities.Add("Bernstein");
            cities.Add("Bildein");
            cities.Add("Bocksdorf");
            cities.Add("Breitenbrunn am Neusiedler See");
            cities.Add("Bruckneudorf");
            cities.Add("Burgauberg-Neudauberg");
            cities.Add("Deutsch Jahrndorf");
            cities.Add("Deutsch Kaltenbrunn");
            cities.Add("Deutsch Schützen-Eisenberg");
            cities.Add("Deutschkreutz");
            cities.Add("Donnerskirchen");
            cities.Add("Draßburg");
            cities.Add("Draßmarkt");
            cities.Add("Eberau");
            cities.Add("Edelstal");
            cities.Add("Eisenstadt");
            cities.Add("Eltendorf");
            cities.Add("Forchtenstein");
            cities.Add("Frankenau-Unterpullendorf");
            cities.Add("Frauenkirchen");
            cities.Add("Gattendorf");
            cities.Add("Gerersdorf-Sulz");
            cities.Add("Gols");
            cities.Add("Grafenschachen");
            cities.Add("Großhöflein");
            cities.Add("Großmürbisch");
            cities.Add("Großpetersdorf");
            cities.Add("Großwarasdorf");
            cities.Add("Güssing");
            cities.Add("Güttenbach");
            cities.Add("Hackerberg");
            cities.Add("Halbturn");
            cities.Add("Hannersdorf");
            cities.Add("Heiligenbrunn");
            cities.Add("Heiligenkreuz im Lafnitztal");
            cities.Add("Heugraben");
            cities.Add("Hirm");
            cities.Add("Horitschon");
            cities.Add("Hornstein");
            cities.Add("Illmitz");
            cities.Add("Inzenhof");
            cities.Add("Jabing");
            cities.Add("Jennersdorf");
            cities.Add("Jois");
            cities.Add("Kaisersdorf");
            cities.Add("Kemeten");
            cities.Add("Kittsee");
            cities.Add("Kleinmürbisch");
            cities.Add("Klingenbach");
            cities.Add("Kobersdorf");
            cities.Add("Kohfidisch");
            cities.Add("Königsdorf");
            cities.Add("Krensdorf");
            cities.Add("Kukmirn");
            cities.Add("Lackenbach");
            cities.Add("Lackendorf");
            cities.Add("Leithaprodersdorf");
            cities.Add("Litzelsdorf");
            cities.Add("Lockenhaus");
            cities.Add("Loipersbach im Burgenland");
            cities.Add("Loipersdorf-Kitzladen");
            cities.Add("Loretto");
            cities.Add("Lutzmannsburg");
            cities.Add("Mannersdorf an der Rabnitz");
            cities.Add("Mariasdorf");
            cities.Add("Markt Allhau");
            cities.Add("Markt Neuhodis");
            cities.Add("Markt Sankt Martin");
            cities.Add("Marz");
            cities.Add("Mattersburg");
            cities.Add("Minihof-Liebau");
            cities.Add("Mischendorf");
            cities.Add("Mogersdorf");
            cities.Add("Mönchhof");
            cities.Add("Mörbisch am See");
            cities.Add("Moschendorf");
            cities.Add("Mühlgraben");
            cities.Add("Müllendorf");
            cities.Add("Neckenmarkt");
            cities.Add("Neuberg im Burgenland");
            cities.Add("Neudörf");
            cities.Add("Neudörfl");
            cities.Add("Neufeld an der Leitha");
            cities.Add("Neuhaus am Klausenbach");
            cities.Add("Neusiedl am See");
            cities.Add("Neustift an der Lafnitz");
            cities.Add("Neustift bei Güssing");
            cities.Add("Neutal");
            cities.Add("Nickelsdorf");
            cities.Add("Nikitsch");
            cities.Add("Oberdorf im Burgenland");
            cities.Add("Oberloisdorf");
            cities.Add("Oberpullendorf");
            cities.Add("Oberschützen");
            cities.Add("Oberwart");
            cities.Add("Oggau am Neusiedler See");
            cities.Add("Olbendorf");
            cities.Add("Ollersdorf im Burgenland");
            cities.Add("Oslip");
            cities.Add("Pama");
            cities.Add("Pamhagen");
            cities.Add("Parndorf");
            cities.Add("Pilgersdorf");
            cities.Add("Pinkafeld");
            cities.Add("Piringsdorf");
            cities.Add("Podersdorf am See");
            cities.Add("Pöttelsdorf");
            cities.Add("Pöttsching");
            cities.Add("Potzneusiedl");
            cities.Add("Purbach am Neusiedlersee");
            cities.Add("Raiding");
            cities.Add("Rauchwart");
            cities.Add("Rechnitz");
            cities.Add("Riedlingsdorf");
            cities.Add("Ritzing");
            cities.Add("Rohr im Burgenland");
            cities.Add("Rohrbach bei Mattersburg");
            cities.Add("Rotenturm an der Pinka");
            cities.Add("Rudersdorf");
            cities.Add("Rust");
            cities.Add("Sankt Andrä am Zicksee");
            cities.Add("Sankt Margarethen im Burgenland");
            cities.Add("Sankt Martin an der Raab");
            cities.Add("Sankt Michael im Burgenland");
            cities.Add("Schachendorf");
            cities.Add("Schandorf");
            cities.Add("Schattendorf");
            cities.Add("Schützen am Gebirge");
            cities.Add("Siegendorf");
            cities.Add("Sieggraben");
            cities.Add("Sigleß");
            cities.Add("Stadtschlaining");
            cities.Add("Stegersbach");
            cities.Add("Steinberg-Dörfl");
            cities.Add("Steinbrunn");
            cities.Add("Stinatz");
            cities.Add("Stoob");
            cities.Add("Stotzing");
            cities.Add("Strem");
            cities.Add("Tadten");
            cities.Add("Tobaj");
            cities.Add("Trausdorf an der Wulka");
            cities.Add("Tschanigraben");
            cities.Add("Unterfrauenhaid");
            cities.Add("Unterkohlstätten");
            cities.Add("Unterrabnitz-Schwendgraben");
            cities.Add("Unterwart");
            cities.Add("Wallern im Burgenland");
            cities.Add("Weichselbaum");
            cities.Add("Weiden am See");
            cities.Add("Weiden bei Rechnitz");
            cities.Add("Weingraben");
            cities.Add("Weppersdorf");
            cities.Add("Wiesen");
            cities.Add("Wiesfleck");
            cities.Add("Wimpassing an der Leitha");
            cities.Add("Winden am See");
            cities.Add("Wolfau");
            cities.Add("Wörterberg");
            cities.Add("Wulkaprodersdorf");
            cities.Add("Zagersdorf");
            cities.Add("Zemendorf-Stöttera");
            cities.Add("Zillingtal");
            cities.Add("Zurndorf");
            cities.Add("Afritz am See");
            cities.Add("Albeck");
            cities.Add("Althofen");
            cities.Add("Arnoldstein");
            cities.Add("Arriach");
            cities.Add("Bad Bleiberg");
            cities.Add("Bad Kleinkirchheim");
            cities.Add("Bad Sankt Leonhard im Lavanttal");
            cities.Add("Baldramsdorf");
            cities.Add("Berg im Drautal");
            cities.Add("Bleiburg");
            cities.Add("Brückl");
            cities.Add("Dellach");
            cities.Add("Dellach im Drautal");
            cities.Add("Deutsch-Griffen");
            cities.Add("Diex");
            cities.Add("Ebenthal in Kärnten");
            cities.Add("Eberndorf");
            cities.Add("Eberstein");
            cities.Add("Eisenkappel-Vellach");
            cities.Add("Feistritz an der Gail");
            cities.Add("Feistritz im Rosental");
            cities.Add("Feistritz ob Bleiburg");
            cities.Add("Feld am See");
            cities.Add("Feldkirchen in Kärnten");
            cities.Add("Ferlach");
            cities.Add("Ferndorf");
            cities.Add("Finkenstein am Faaker See");
            cities.Add("Flattach");
            cities.Add("Frantschach-Sankt Gertraud");
            cities.Add("Frauenstein");
            cities.Add("Fresach");
            cities.Add("Friesach");
            cities.Add("Gallizien");
            cities.Add("Gitschtal");
            cities.Add("Glanegg");
            cities.Add("Globasnitz");
            cities.Add("Glödnitz");
            cities.Add("Gmünd in Kärnten");
            cities.Add("Gnesau");
            cities.Add("Grafenstein");
            cities.Add("Greifenburg");
            cities.Add("Griffen");
            cities.Add("Großkirchheim");
            cities.Add("Gurk");
            cities.Add("Guttaring");
            cities.Add("Heiligenblut am Großglockner");
            cities.Add("Hermagor-Pressegger See");
            cities.Add("Himmelberg");
            cities.Add("Hohenthurn");
            cities.Add("Hüttenberg");
            cities.Add("Irschen");
            cities.Add("Kappel am Krappfeld");
            cities.Add("Keutschach am See");
            cities.Add("Kirchbach");
            cities.Add("Klagenfurt am Wörthersee");
            cities.Add("Kleblach-Lind");
            cities.Add("Klein Sankt Paul");
            cities.Add("Kötschach-Mauthen");
            cities.Add("Köttmannsdorf");
            cities.Add("Krems in Kärnten");
            cities.Add("Krumpendorf am Wörthersee");
            cities.Add("Lavamünd");
            cities.Add("Lendorf");
            cities.Add("Lesachtal");
            cities.Add("Liebenfels");
            cities.Add("Ludmannsdorf");
            cities.Add("Lurnfeld");
            cities.Add("Magdalensberg");
            cities.Add("Mallnitz");
            cities.Add("Malta");
            cities.Add("Maria Rain");
            cities.Add("Maria Saal");
            cities.Add("Maria Wörth");
            cities.Add("Metnitz");
            cities.Add("Micheldorf");
            cities.Add("Millstatt am See");
            cities.Add("Mölbling");
            cities.Add("Moosburg");
            cities.Add("Mörtschach");
            cities.Add("Mühldorf");
            cities.Add("Neuhaus");
            cities.Add("Nötsch im Gailtal");
            cities.Add("Oberdrauburg");
            cities.Add("Obervellach");
            cities.Add("Ossiach");
            cities.Add("Paternion");
            cities.Add("Poggersdorf");
            cities.Add("Pörtschach am Wörthersee");
            cities.Add("Preitenegg");
            cities.Add("Radenthein");
            cities.Add("Rangersdorf");
            cities.Add("Reichenau");
            cities.Add("Reichenfels");
            cities.Add("Reißeck");
            cities.Add("Rennweg am Katschberg");
            cities.Add("Rosegg");
            cities.Add("Ruden");
            cities.Add("Schiefling am Wörthersee");
            cities.Add("Seeboden am Millstätter See");
            cities.Add("Sittersdorf");
            cities.Add("Spittal an der Drau");
            cities.Add("Sankt Andrä");
            cities.Add("Sankt Georgen am Längsee");
            cities.Add("Sankt Georgen im Lavanttal");
            cities.Add("Sankt Jakob im Rosental");
            cities.Add("Sankt Kanzian am Klopeiner See");
            cities.Add("Sankt Margareten im Rosental");
            cities.Add("Sankt Paul im Lavanttal");
            cities.Add("Sankt Stefan im Gailtal");
            cities.Add("Sankt Urban");
            cities.Add("Sankt Veit an der Glan");
            cities.Add("Stall");
            cities.Add("Steindorf am Ossiacher See");
            cities.Add("Steinfeld");
            cities.Add("Steuerberg");
            cities.Add("Stockenboi");
            cities.Add("Straßburg");
            cities.Add("Techelsberg am Wörther See");
            cities.Add("Trebesing");
            cities.Add("Treffen am Ossiacher See");
            cities.Add("Velden am Wörther See");
            cities.Add("Villach");
            cities.Add("Völkermarkt");
            cities.Add("Weißensee");
            cities.Add("Weißenstein");
            cities.Add("Weitensfeld im Gurktal");
            cities.Add("Wernberg");
            cities.Add("Winklern");
            cities.Add("Wolfsberg");
            cities.Add("Zell");
            cities.Add("Absdorf");
            cities.Add("Achau");
            cities.Add("Aderklaa");
            cities.Add("Aggsbach");
            cities.Add("Alberndorf im Pulkautal");
            cities.Add("Albrechtsberg an der Großen Krems");
            cities.Add("Alland");
            cities.Add("Allentsteig");
            cities.Add("Allhartsberg");
            cities.Add("Altenburg");
            cities.Add("Altendorf");
            cities.Add("Altenmarkt an der Triesting");
            cities.Add("Altlengbach");
            cities.Add("Altlichtenwarth");
            cities.Add("Altmelon");
            cities.Add("Amaliendorf-Aalfang");
            cities.Add("Amstetten");
            cities.Add("Andlersdorf");
            cities.Add("Angern an der March");
            cities.Add("Annaberg");
            cities.Add("Arbesbach");
            cities.Add("Ardagger");
            cities.Add("Artstetten-Pöbring");
            cities.Add("Aschbach-Markt");
            cities.Add("Aspangberg-Sankt Peter");
            cities.Add("Aspang-Markt");
            cities.Add("Asparn an der Zaya");
            cities.Add("Asperhofen");
            cities.Add("Atzenbrugg");
            cities.Add("Au am Leithaberge");
            cities.Add("Auersthal");
            cities.Add("Bad Deutsch-Altenburg");
            cities.Add("Bad Erlach");
            cities.Add("Bad Fischau-Brunn");
            cities.Add("Bad Großpertholz");
            cities.Add("Bad Pirawarth");
            cities.Add("Bad Schönau");
            cities.Add("Bad Traunstein");
            cities.Add("Bad Vöslau");
            cities.Add("Baden bei Wien");
            cities.Add("Bärnkopf");
            cities.Add("Behamberg");
            cities.Add("Berg");
            cities.Add("Bergern im Dunkelsteinerwald");
            cities.Add("Bergland");
            cities.Add("Berndorf");
            cities.Add("Bernhardsthal");
            cities.Add("Biberbach");
            cities.Add("Biedermannsdorf");
            cities.Add("Bisamberg");
            cities.Add("Bischofstetten");
            cities.Add("Blindenmarkt");
            cities.Add("Blumau-Neurißhof");
            cities.Add("Bockfließ");
            cities.Add("Böheimkirchen");
            cities.Add("Brand-Laaben");
            cities.Add("Brand-Nagelberg");
            cities.Add("Breitenau");
            cities.Add("Breitenfurt bei Wien");
            cities.Add("Breitenstein");
            cities.Add("Bromberg");
            cities.Add("Bruck an der Leitha");
            cities.Add("Brunn am Gebirge");
            cities.Add("Brunn an der Wild");
            cities.Add("Buchbach");
            cities.Add("Burgschleinitz-Kühnring");
            cities.Add("Bürg-Vöstenhof");
            cities.Add("Deutsch-Wagram");
            cities.Add("Dietmanns");
            cities.Add("Dobersberg");
            cities.Add("Dorfstetten");
            cities.Add("Drasenhofen");
            cities.Add("Drosendorf-Zissersdorf");
            cities.Add("Drösing");
            cities.Add("Droß");
            cities.Add("Dunkelsteinerwald");
            cities.Add("Dürnkrut");
            cities.Add("Dürnstein");
            cities.Add("Ebenfurth");
            cities.Add("Ebenthal");
            cities.Add("Ebergassing");
            cities.Add("Ebreichsdorf");
            cities.Add("Echsenbach");
            cities.Add("Eckartsau");
            cities.Add("Edlitz");
            cities.Add("Eggenburg");
            cities.Add("Eggendorf");
            cities.Add("Eggern");
            cities.Add("Eichgraben");
            cities.Add("Eisgarn");
            cities.Add("Emmersdorf an der Donau");
            cities.Add("Engelhartstetten");
            cities.Add("Ennsdorf");
            cities.Add("Enzenreith");
            cities.Add("Enzersdorf an der Fischa");
            cities.Add("Enzersfeld im Weinviertel");
            cities.Add("Enzesfeld-Lindabrunn");
            cities.Add("Erlauf");
            cities.Add("Ernstbrunn");
            cities.Add("Ernsthofen");
            cities.Add("Ertl");
            cities.Add("Eschenau");
            cities.Add("Euratsfeld");
            cities.Add("Falkenstein");
            cities.Add("Fallbach");
            cities.Add("Feistritz am Wechsel");
            cities.Add("Felixdorf");
            cities.Add("Fels am Wagram");
            cities.Add("Ferschnitz");
            cities.Add("Fischamend");
            cities.Add("Frankenfels");
            cities.Add("Furth an der Triesting");
            cities.Add("Furth bei Göttweig");
            cities.Add("Gaaden");
            cities.Add("Gablitz");
            cities.Add("Gaming");
            cities.Add("Gänserndorf");
            cities.Add("Gars am Kamp");
            cities.Add("Gastern");
            cities.Add("Gaubitsch");
            cities.Add("Gaweinstal");
            cities.Add("Gedersdorf");
            cities.Add("Geras");
            cities.Add("Gerasdorf bei Wien");
            cities.Add("Gerersdorf");
            cities.Add("Gföhl");
            cities.Add("Gießhübl");
            cities.Add("Glinzendorf");
            cities.Add("Gloggnitz");
            cities.Add("Gmünd");
            cities.Add("Gnadendorf");
            cities.Add("Göllersdorf");
            cities.Add("Golling an der Erlauf");
            cities.Add("Göpfritz an der Wild");
            cities.Add("Göstling an der Ybbs");
            cities.Add("Göttlesbrunn-Arbesthal");
            cities.Add("Götzendorf an der Leitha");
            cities.Add("Grabern");
            cities.Add("Grafenbach-Sankt Valentin");
            cities.Add("Grafenegg");
            cities.Add("Grafenschlag");
            cities.Add("Grafenwörth");
            cities.Add("Gramatneusiedl");
            cities.Add("Gresten");
            cities.Add("Gresten-Land");
            cities.Add("Grimmenstein");
            cities.Add("Groß Gerungs");
            cities.Add("Großdietmanns");
            cities.Add("Großebersdorf");
            cities.Add("Großengersdorf");
            cities.Add("Groß-Enzersdorf");
            cities.Add("Großgöttfritz");
            cities.Add("Großharras");
            cities.Add("Großhofen");
            cities.Add("Großkrut");
            cities.Add("Großmugl");
            cities.Add("Großriedenthal");
            cities.Add("Großrußbach");
            cities.Add("Großschönau");
            cities.Add("Groß-Schweinbarth");
            cities.Add("Groß-Siegharts");
            cities.Add("Großweikersdorf");
            cities.Add("Grünbach am Schneeberg");
            cities.Add("Gumpoldskirchen");
            cities.Add("Günselsdorf");
            cities.Add("Guntersdorf");
            cities.Add("Guntramsdorf");
            cities.Add("Gutenbrunn");
            cities.Add("Gutenstein");
            cities.Add("Haag");
            cities.Add("Hadersdorf-Kammern");
            cities.Add("Hadres");
            cities.Add("Hafnerbach");
            cities.Add("Hagenbrunn");
            cities.Add("Haidershofen");
            cities.Add("Hainburg an der Donau");
            cities.Add("Hainfeld");
            cities.Add("Hardegg");
            cities.Add("Haringsee");
            cities.Add("Harmannsdorf");
            cities.Add("Haslau-Maria Ellend");
            cities.Add("Haugschlag");
            cities.Add("Haugsdorf");
            cities.Add("Haunoldstein");
            cities.Add("Hausbrunn");
            cities.Add("Hauskirchen");
            cities.Add("Hausleiten");
            cities.Add("Heidenreichstein");
            cities.Add("Heiligenkreuz");
            cities.Add("Heldenberg");
            cities.Add("Hennersdorf bei Wien");
            cities.Add("Hernstein");
            cities.Add("Herrnbaumgarten");
            cities.Add("Herzogenburg");
            cities.Add("Himberg");
            cities.Add("Hinterbrühl");
            cities.Add("Hirschbach");
            cities.Add("Hirtenberg");
            cities.Add("Hochleithen");
            cities.Add("Hochneukirchen-Gschaidt");
            cities.Add("Hochwolkersdorf");
            cities.Add("Hof am Leithaberge");
            cities.Add("Hofamt Priel");
            cities.Add("Höflein");
            cities.Add("Höflein an der Hohen Wand");
            cities.Add("Hofstetten-Grünau");
            cities.Add("Hohe Wand");
            cities.Add("Hohenau an der March");
            cities.Add("Hohenberg");
            cities.Add("Hoheneich");
            cities.Add("Hohenruppersdorf");
            cities.Add("Hohenwarth-Mühlbach am Manhartsberg");
            cities.Add("Hollabrunn");
            cities.Add("Hollenstein an der Ybbs");
            cities.Add("Hollenthon");
            cities.Add("Horn");
            cities.Add("Hundsheim");
            cities.Add("Hürm");
            cities.Add("Inzersdorf-Getzersdorf");
            cities.Add("Irnfritz-Messern");
            cities.Add("Jaidhof");
            cities.Add("Japons");
            cities.Add("Jedenspeigen");
            cities.Add("Judenau-Baumgarten");
            cities.Add("Kaltenleutgeben");
            cities.Add("Kapelln");
            cities.Add("Karlstein an der Thaya");
            cities.Add("Karlstetten");
            cities.Add("Kasten bei Böheimkirchen");
            cities.Add("Katzelsdorf");
            cities.Add("Kaumberg");
            cities.Add("Kautzen");
            cities.Add("Kematen an der Ybbs");
            cities.Add("Kilb");
            cities.Add("Kirchberg am Wagram");
            cities.Add("Kirchberg am Walde");
            cities.Add("Kirchberg am Wechsel");
            cities.Add("Kirchberg an der Pielach");
            cities.Add("Kirchschlag");
            cities.Add("Kirchschlag in der Buckligen Welt");
            cities.Add("Kirchstetten");
            cities.Add("Kirnberg an der Mank");
            cities.Add("Klausen-Leopoldsdorf");
            cities.Add("Klein-Neusiedl");
            cities.Add("Klein-Pöchlarn");
            cities.Add("Kleinzell");
            cities.Add("Klosterneuburg");
            cities.Add("Königsbrunn am Wagram");
            cities.Add("Königstetten");
            cities.Add("Korneuburg");
            cities.Add("Kottes-Purk");
            cities.Add("Kottingbrunn");
            cities.Add("Krems an der Donau");
            cities.Add("Kreuttal");
            cities.Add("Kreuzstetten");
            cities.Add("Krumau am Kamp");
            cities.Add("Krumbach");
            cities.Add("Krummnußbaum");
            cities.Add("Laa an der Thaya");
            cities.Add("Laab im Walde");
            cities.Add("Ladendorf");
            cities.Add("Langau");
            cities.Add("Langenlois");
            cities.Add("Langenrohr");
            cities.Add("Langenzersdorf");
            cities.Add("Langschlag");
            cities.Add("Lanzendorf");
            cities.Add("Lanzenkirchen");
            cities.Add("Lassee");
            cities.Add("Laxenburg");
            cities.Add("Leiben");
            cities.Add("Leitzersdorf");
            cities.Add("Lengenfeld");
            cities.Add("Leobendorf");
            cities.Add("Leobersdorf");
            cities.Add("Leopoldsdorf");
            cities.Add("Leopoldsdorf im Marchfelde");
            cities.Add("Lichtenau im Waldviertel");
            cities.Add("Lichtenegg");
            cities.Add("Lichtenwörth");
            cities.Add("Lilienfeld");
            cities.Add("Litschau");
            cities.Add("Loich");
            cities.Add("Loosdorf");
            cities.Add("Ludweis-Aigen");
            cities.Add("Lunz am See");
            cities.Add("Mailberg");
            cities.Add("Maissau");
            cities.Add("Mank");
            cities.Add("Mannersdorf am Leithagebirge");
            cities.Add("Mannsdorf an der Donau");
            cities.Add("Marbach an der Donau");
            cities.Add("Marchegg");
            cities.Add("Maria Enzersdorf");
            cities.Add("Maria Laach am Jauerling");
            cities.Add("Maria Taferl");
            cities.Add("Maria Anzbach");
            cities.Add("Maria Lanzendorf");
            cities.Add("Markersdorf-Haindorf");
            cities.Add("Markgrafneusiedl");
            cities.Add("Markt Piesting");
            cities.Add("Martinsberg");
            cities.Add("Matzendorf-Hölles");
            cities.Add("Matzen-Raggendorf");
            cities.Add("Mauerbach");
            cities.Add("Mautern an der Donau");
            cities.Add("Meiseldorf");
            cities.Add("Melk");
            cities.Add("Michelbach");
            cities.Add("Michelhausen");
            cities.Add("Miesenbach");
            cities.Add("Mistelbach");
            cities.Add("Mitterbach am Erlaufsee");
            cities.Add("Mitterndorf an der Fischa");
            cities.Add("Mödling");
            cities.Add("Mönichkirchen");
            cities.Add("Moorbad Harbach");
            cities.Add("Moosbrunn");
            cities.Add("Muckendorf-Wipfing");
            cities.Add("Muggendorf");
            cities.Add("Mühldorf");
            cities.Add("Münchendorf");
            cities.Add("Münichreith-Laimbach");
            cities.Add("Nappersdorf-Kammersdorf");
            cities.Add("Natschbach-Loipersbach");
            cities.Add("Neidling");
            cities.Add("Neudorf bei Staatz");
            cities.Add("Neuhofen an der Ybbs");
            cities.Add("Neulengbach");
            cities.Add("Neumarkt an der Ybbs");
            cities.Add("Neunkirchen");
            cities.Add("Neusiedl an der Zaya");
            cities.Add("Neustadtl an der Donau");
            cities.Add("Neustift-Innermanzing");
            cities.Add("Niederhollabrunn");
            cities.Add("Niederleis");
            cities.Add("Nöchling");
            cities.Add("Nußdorf ob der Traisen");
            cities.Add("Ober-Grafendorf");
            cities.Add("Oberndorf an der Melk");
            cities.Add("Obersiebenbrunn");
            cities.Add("Oberwaltersdorf");
            cities.Add("Obritzberg-Rust");
            cities.Add("Oed-Öhling");
            cities.Add("Opponitz");
            cities.Add("Orth an der Donau");
            cities.Add("Ottenschlag");
            cities.Add("Ottenthal");
            cities.Add("Otterthal");
            cities.Add("Palterndorf-Dobermannsdorf");
            cities.Add("Parbasdorf");
            cities.Add("Paudorf");
            cities.Add("Payerbach");
            cities.Add("Perchtoldsdorf");
            cities.Add("Pernegg");
            cities.Add("Pernersdorf");
            cities.Add("Pernitz");
            cities.Add("Persenbeug-Gottsdorf");
            cities.Add("Petronell-Carnuntum");
            cities.Add("Petzenkirchen");
            cities.Add("Pfaffenschlag bei Waidhofen");
            cities.Add("Pfaffstätten");
            cities.Add("Pillichsdorf");
            cities.Add("Pitten");
            cities.Add("Pöchlarn");
            cities.Add("Pöggstall");
            cities.Add("Pölla");
            cities.Add("Pottendorf");
            cities.Add("Pottenstein");
            cities.Add("Poysdorf");
            cities.Add("Prellenkirchen");
            cities.Add("Pressbaum");
            cities.Add("Prigglitz");
            cities.Add("Prinzersdorf");
            cities.Add("Prottes");
            cities.Add("Pürschling");
            cities.Add("Puchberg am Schneeberg");
            cities.Add("Puchenstuben");
            cities.Add("Pulkau");
            cities.Add("Purgstall an der Erlauf");
            cities.Add("Purkersdorf");
            cities.Add("Pyhra");
            cities.Add("Raabs an der Thaya");
            cities.Add("Raach am Hochgebirge");
            cities.Add("Raasdorf");
            cities.Add("Rabensburg");
            cities.Add("Rabenstein an der Pielach");
            cities.Add("Ramsau");
            cities.Add("Randegg");
            cities.Add("Rappottenstein");
            cities.Add("Rastenfeld");
            cities.Add("Rauchenwarth");
            cities.Add("Ravelsbach");
            cities.Add("Raxendorf");
            cities.Add("Reichenau an der Rax");
            cities.Add("Reingers");
            cities.Add("Reinsberg");
            cities.Add("Reisenberg");
            cities.Add("Retz");
            cities.Add("Retzbach");
            cities.Add("Ringelsdorf-Niederabsdorf");
            cities.Add("Rohr im Gebirge");
            cities.Add("Rohrau");
            cities.Add("Rohrbach an der Gölsen");
            cities.Add("Röhrenbach");
            cities.Add("Rohrendorf bei Krems");
            cities.Add("Röschitz");
            cities.Add("Rosenburg-Mold");
            cities.Add("Rossatz-Arnsdorf");
            cities.Add("Ruprechtshofen");
            cities.Add("Rußbach");
            cities.Add("Sallingberg");
            cities.Add("Scharndorf");
            cities.Add("Scheibbs");
            cities.Add("Scheiblingkirchen-Thernberg");
            cities.Add("Schollach");
            cities.Add("Schönau an der Triesting");
            cities.Add("Schönbach");
            cities.Add("Schönberg am Kamp");
            cities.Add("Schönbühel-Aggsbach");
            cities.Add("Schönkirchen-Reyersdorf");
            cities.Add("Schottwien");
            cities.Add("Schrattenbach");
            cities.Add("Schrattenberg");
            cities.Add("Schrattenthal");
            cities.Add("Schrems");
            cities.Add("Schwadorf");
            cities.Add("Schwarzau am Steinfeld");
            cities.Add("Schwarzau im Gebirge");
            cities.Add("Schwarzenau");
            cities.Add("Schwarzenbach");
            cities.Add("Schwarzenbach an der Pielach");
            cities.Add("Schwechat");
            cities.Add("Schweiggers");
            cities.Add("Seebenstein");
            cities.Add("Seefeld-Kadolz");
            cities.Add("Seibersdorf");
            cities.Add("Seitenstetten");
            cities.Add("Semmering");
            cities.Add("Senftenberg");
            cities.Add("Sieghartskirchen");
            cities.Add("Sierndorf");
            cities.Add("Sigmundsherberg");
            cities.Add("Sitzenberg-Reidling");
            cities.Add("Sitzendorf an der Schmida");
            cities.Add("Sollenau");
            cities.Add("Sommerein");
            cities.Add("Sonntagberg");
            cities.Add("Sooß");
            cities.Add("Spannberg");
            cities.Add("Spillern");
            cities.Add("Spitz");
            cities.Add("Sankt Aegyd am Neuwalde");
            cities.Add("Sankt Andrä-Wördern");
            cities.Add("Sankt Anton an der Jeßnitz");
            cities.Add("Sankt Bernhard-Frauenhofen");
            cities.Add("Sankt Corona am Wechsel");
            cities.Add("Sankt Egyden am Steinfeld");
            cities.Add("Sankt Georgen am Reith");
            cities.Add("Sankt Georgen am Ybbsfelde");
            cities.Add("Sankt Georgen an der Leys");
            cities.Add("Sankt Leonhard am Forst");
            cities.Add("Sankt Leonhard am Hornerwald");
            cities.Add("Sankt Margarethen an der Sierning");
            cities.Add("Sankt Martin");
            cities.Add("Sankt Martin-Karlsbach");
            cities.Add("Sankt Oswald");
            cities.Add("Sankt Pantaleon-Erla");
            cities.Add("Sankt Peter in der Au");
            cities.Add("Sankt Pölten");
            cities.Add("St. Valentin");
            cities.Add("Sankt Veit an der Gölsen");
            cities.Add("Staatz");
            cities.Add("Statzendorf");
            cities.Add("Steinakirchen am Forst");
            cities.Add("Stetteldorf am Wagram");
            cities.Add("Stetten");
            cities.Add("Stockerau");
            cities.Add("Stössing");
            cities.Add("Straning-Grafenberg");
            cities.Add("Straß im Straßertale");
            cities.Add("Strasshof an der Nordbahn");
            cities.Add("Stratzing");
            cities.Add("Strengberg");
            cities.Add("Stronsdorf");
            cities.Add("Sulz im Weinviertel");
            cities.Add("Tattendorf");
            cities.Add("Teesdorf");
            cities.Add("Ternitz");
            cities.Add("Texingtal");
            cities.Add("Thaya");
            cities.Add("Theresienfeld");
            cities.Add("Thomasberg");
            cities.Add("Traisen");
            cities.Add("Traiskirchen");
            cities.Add("Traismauer");
            cities.Add("Trattenbach");
            cities.Add("Trautmannsdorf an der Leitha");
            cities.Add("Trumau");
            cities.Add("Tulbing");
            cities.Add("Tulln an der Donau");
            cities.Add("Tullnerbach");
            cities.Add("Türnitz");
            cities.Add("Ulrichskirchen-Schleinbach");
            cities.Add("Unserfrau-Altweitra");
            cities.Add("Untersiebenbrunn");
            cities.Add("Unterstinkenbrunn");
            cities.Add("Velm-Götzendorf");
            cities.Add("Viehdorf");
            cities.Add("Vitis");
            cities.Add("Vösendorf");
            cities.Add("Waidhofen an der Thaya");
            cities.Add("Waidhofen an der Thaya-Land");
            cities.Add("Waidhofen an der Ybbs");
            cities.Add("Waidmannsfeld");
            cities.Add("Waldegg");
            cities.Add("Waldenstein");
            cities.Add("Waldhausen");
            cities.Add("Waldkirchen an der Thaya");
            cities.Add("Wallsee-Sindelburg");
            cities.Add("Walpersbach");
            cities.Add("Wang");
            cities.Add("Warth");
            cities.Add("Wartmannstetten");
            cities.Add("Weiden an der March");
            cities.Add("Weikendorf");
            cities.Add("Weikersdorf am Steinfelde");
            cities.Add("Weinburg");
            cities.Add("Weinzierl am Walde");
            cities.Add("Weissenbach an der Triesting");
            cities.Add("Weißenkirchen in der Wachau");
            cities.Add("Weistrach");
            cities.Add("Weiten");
            cities.Add("Weitersfeld");
            cities.Add("Weitra");
            cities.Add("Wiener Neudorf");
            cities.Add("Wiener Neustadt");
            cities.Add("Wienerwald");
            cities.Add("Wieselburg");
            cities.Add("Wieselburg-Land");
            cities.Add("Wiesmath");
            cities.Add("Wildendürnbach");
            cities.Add("Wilfersdorf");
            cities.Add("Wilhelmsburg");
            cities.Add("Willendorf");
            cities.Add("Wimpassing im Schwarzatale");
            cities.Add("Windigsteig");
            cities.Add("Winklarn");
            cities.Add("Winzendorf-Muthmannsdorf");
            cities.Add("Wölbling");
            cities.Add("Wolfpassing");
            cities.Add("Wolfsbach");
            cities.Add("Wolfsgraben");
            cities.Add("Wolfsthal");
            cities.Add("Wolkersdorf im Weinviertel");
            cities.Add("Wöllersdorf-Steinabrückl");
            cities.Add("Wullersdorf");
            cities.Add("Würflach");
            cities.Add("Würmla");
            cities.Add("Ybbs an der Donau");
            cities.Add("Ybbsitz");
            cities.Add("Yspertal");
            cities.Add("Zeillern");
            cities.Add("Zeiselmauer-Wolfpassing");
            cities.Add("Zelking-Matzleinsdorf");
            cities.Add("Zellerndorf");
            cities.Add("Ziersdorf");
            cities.Add("Zillingdorf");
            cities.Add("Zistersdorf");
            cities.Add("Zöbern");
            cities.Add("Zwentendorf an der Donau");
            cities.Add("Zwettl");
            cities.Add("Zwölfaxing");
            cities.Add("Abtenau");
            cities.Add("Adnet");
            cities.Add("Altenmarkt im Pongau");
            cities.Add("Anif");
            cities.Add("Annaberg-Lungötz");
            cities.Add("Anthering");
            cities.Add("Bad Gastein");
            cities.Add("Bad Hofgastein");
            cities.Add("Bad Vigaun");
            cities.Add("Bergheim");
            cities.Add("Berndorf bei Salzburg");
            cities.Add("Bischofshofen");
            cities.Add("Bramberg am Wildkogel");
            cities.Add("Bruck an der Großglocknerstraße");
            cities.Add("Bürmoos");
            cities.Add("Dienten am Hochkönig");
            cities.Add("Dorfbeuern");
            cities.Add("Dorfgastein");
            cities.Add("Eben im Pongau");
            cities.Add("Ebenau");
            cities.Add("Elixhausen");
            cities.Add("Elsbethen");
            cities.Add("Eugendorf");
            cities.Add("Faistenau");
            cities.Add("Filzmoos");
            cities.Add("Flachau");
            cities.Add("Forstau");
            cities.Add("Fusch an der Großglocknerstraße");
            cities.Add("Fuschl am See");
            cities.Add("Goldegg");
            cities.Add("Golling an der Salzach");
            cities.Add("Göming");
            cities.Add("Göriach");
            cities.Add("Grödig");
            cities.Add("Großarl");
            cities.Add("Großgmain");
            cities.Add("Hallein");
            cities.Add("Hallwang");
            cities.Add("Henndorf am Wallersee");
            cities.Add("Hintersee");
            cities.Add("Hof bei Salzburg");
            cities.Add("Hollersbach im Pinzgau");
            cities.Add("Hüttau");
            cities.Add("Hüttschlag");
            cities.Add("Kaprun");
            cities.Add("Kleinarl");
            cities.Add("Koppl");
            cities.Add("Köstendorf");
            cities.Add("Krimml");
            cities.Add("Krispl");
            cities.Add("Kuchl");
            cities.Add("Lamprechtshausen");
            cities.Add("Lend");
            cities.Add("Leogang");
            cities.Add("Lessach");
            cities.Add("Lofer");
            cities.Add("Maishofen");
            cities.Add("Maria Alm");
            cities.Add("Mariapfarr");
            cities.Add("Mattsee");
            cities.Add("Mauterndorf");
            cities.Add("Mittersill");
            cities.Add("Mühlbach am Hochkönig");
            cities.Add("Muhr");
            cities.Add("Neukirchen am Großvenediger");
            cities.Add("Neumarkt am Wallersee");
            cities.Add("Niedernsill");
            cities.Add("Nußdorf am Haunsberg");
            cities.Add("Oberalm");
            cities.Add("Oberndorf bei Salzburg");
            cities.Add("Obertrum");
            cities.Add("Pfarrwerfen");
            cities.Add("Piesendorf");
            cities.Add("Plainfeld");
            cities.Add("Puch bei Hallein");
            cities.Add("Radstadt");
            cities.Add("Ramingstein");
            cities.Add("Rauris");
            cities.Add("Rußbach am Paß Gschütt");
            cities.Add("Saalbach-Hinterglemm");
            cities.Add("Saalfelden");
            cities.Add("Salzburg");
            cities.Add("Sankt Andrä im Lungau");
            cities.Add("Sankt Georgen bei Salzburg");
            cities.Add("Sankt Gilgen");
            cities.Add("Sankt Johann im Pongau");
            cities.Add("Sankt Koloman");
            cities.Add("Sankt Margarethen im Lungau");
            cities.Add("Sankt Martin am Tennengebirge");
            cities.Add("Sankt Martin bei Lofer");
            cities.Add("Sankt Michael im Lungau");
            cities.Add("Sankt Veit im Pongau");
            cities.Add("Scheffau am Tennengebirge");
            cities.Add("Schleedorf");
            cities.Add("Schwarzach im Pongau");
            cities.Add("Seeham");
            cities.Add("Seekirchen am Wallersee");
            cities.Add("Straßwalchen");
            cities.Add("Strobl");
            cities.Add("Stuhlfelden");
            cities.Add("Tamsweg");
            cities.Add("Taxenbach");
            cities.Add("Thalgau");
            cities.Add("Thomatal");
            cities.Add("Tweng");
            cities.Add("Unken");
            cities.Add("Unternberg");
            cities.Add("Untertauern");
            cities.Add("Uttendorf");
            cities.Add("Viehhofen");
            cities.Add("Wagrain");
            cities.Add("Wald im Pinzgau");
            cities.Add("Wals-Siezenheim");
            cities.Add("Weißbach bei Lofer");
            cities.Add("Weißpriach");
            cities.Add("Werfen");
            cities.Add("Werfenweng");
            cities.Add("Zederhaus");
            cities.Add("Zell am See");
            cities.Add("Admont");
            cities.Add("Aflenz");
            cities.Add("Aich");
            cities.Add("Aigen im Ennstal");
            cities.Add("Albersdorf-Prebuch");
            cities.Add("Allerheiligen bei Wildon");
            cities.Add("Altaussee");
            cities.Add("Altenmarkt bei Sankt Gallen");
            cities.Add("Anger");
            cities.Add("Ardning");
            cities.Add("Arnfels");
            cities.Add("Bad Aussee");
            cities.Add("Bad Blumau");
            cities.Add("Bad Gleichenberg");
            cities.Add("Bad Mitterndorf");
            cities.Add("Bad Radkersburg");
            cities.Add("Bad Waltersdorf");
            cities.Add("Bärnbach");
            cities.Add("Birkfeld");
            cities.Add("Breitenau am Hochlantsch");
            cities.Add("Bruck an der Mur");
            cities.Add("Buch-Sankt Magdalena");
            cities.Add("Burgau");
            cities.Add("Dechantskirchen");
            cities.Add("Deutsch Goritz");
            cities.Add("Deutschfeistritz");
            cities.Add("Deutschlandsberg");
            cities.Add("Dobl-Zwaring");
            cities.Add("Ebersdorf");
            cities.Add("Edelsbach bei Feldbach");
            cities.Add("Edelschrott");
            cities.Add("Eggersdorf bei Graz");
            cities.Add("Ehrenhausen an der Weinstraße");
            cities.Add("Eibiswald");
            cities.Add("Eichkögl");
            cities.Add("Eisenerz");
            cities.Add("Empersdorf");
            cities.Add("Fehring");
            cities.Add("Feistritztal");
            cities.Add("Feldbach");
            cities.Add("Feldkirchen bei Graz");
            cities.Add("Fernitz-Mellach");
            cities.Add("Fischbach");
            cities.Add("Fladnitz an der Teichalm");
            cities.Add("Floing");
            cities.Add("Fohnsdorf");
            cities.Add("Frauental an der Laßnitz");
            cities.Add("Friedberg");
            cities.Add("Frohnleiten");
            cities.Add("Fürstenfeld");
            cities.Add("Gaal");
            cities.Add("Gabersdorf");
            cities.Add("Gaishorn am See");
            cities.Add("Gamlitz");
            cities.Add("Gasen");
            cities.Add("Geistthal-Södingberg");
            cities.Add("Gersdorf an der Feistritz");
            cities.Add("Gleinstätten");
            cities.Add("Gleisdorf");
            cities.Add("Gnas");
            cities.Add("Gössendorf");
            cities.Add("Grafendorf bei Hartberg");
            cities.Add("Gralla");
            cities.Add("Gratkorn");
            cities.Add("Gratwein-Straßengel");
            cities.Add("Graz");
            cities.Add("Greinbach");
            cities.Add("Gröbming");
            cities.Add("Groß Sankt Florian");
            cities.Add("Großklein");
            cities.Add("Großsteinbach");
            cities.Add("Großwilfersdorf");
            cities.Add("Grundlsee");
            cities.Add("Gutenberg-Stenzengreith");
            cities.Add("Halbenrain");
            cities.Add("Hart bei Graz");
            cities.Add("Hartberg");
            cities.Add("Hartberg Umgebung");
            cities.Add("Hartl");
            cities.Add("Haselsdorf-Tobelbad");
            cities.Add("Haus im Ennstal");
            cities.Add("Hausmannstätten");
            cities.Add("Heiligenkreuz am Waasen");
            cities.Add("Heimschuh");
            cities.Add("Hengsberg");
            cities.Add("Hirschegg-Pack");
            cities.Add("Hitzendorf");
            cities.Add("Hofstätten an der Raab");
            cities.Add("Hohentauern");
            cities.Add("Ilz");
            cities.Add("Ilztal");
            cities.Add("Irdning-Donnersbachtal");
            cities.Add("Jagerberg");
            cities.Add("Judenburg");
            cities.Add("Kainach bei Voitsberg");
            cities.Add("Kainbach bei Graz");
            cities.Add("Kaindorf");
            cities.Add("Kalsdorf bei Graz");
            cities.Add("Kalwang");
            cities.Add("Kammern im Liesingtal");
            cities.Add("Kapfenberg");
            cities.Add("Kapfenstein");
            cities.Add("Kindberg");
            cities.Add("Kirchbach-Zerlach");
            cities.Add("Kirchberg an der Raab");
            cities.Add("Kitzeck im Sausal");
            cities.Add("Klöch");
            cities.Add("Knittelfeld");
            cities.Add("Kobenz");
            cities.Add("Köflach");
            cities.Add("Krakau");
            cities.Add("Kraubath an der Mur");
            cities.Add("Krieglach");
            cities.Add("Krottendorf-Gaisfeld");
            cities.Add("Kumberg");
            cities.Add("Lafnitz");
            cities.Add("Landl");
            cities.Add("Lang");
            cities.Add("Langenwang");
            cities.Add("Lannach");
            cities.Add("Lassing");
            cities.Add("Laßnitzhöhe");
            cities.Add("Lebring-Sankt Margarethen");
            cities.Add("Leibnitz");
            cities.Add("Leoben");
            cities.Add("Leutschach an der Weinstraße");
            cities.Add("Lieboch");
            cities.Add("Liezen");
            cities.Add("Ligist");
            cities.Add("Lobmingtal");
            cities.Add("Loipersdorf bei Fürstenfeld");
            cities.Add("Ludersdorf-Wilfersdorf");
            cities.Add("Maria Lankowitz");
            cities.Add("Mariazell");
            cities.Add("Markt Hartmannsdorf");
            cities.Add("Mautern in Steiermark");
            cities.Add("Mettersdorf am Saßbach");
            cities.Add("Michaelerberg-Pruggern");
            cities.Add("Miesenbach bei Birkfeld");
            cities.Add("Mitterberg-Sankt Martin");
            cities.Add("Mitterdorf an der Raab");
            cities.Add("Mooskirchen");
            cities.Add("Mortantsch");
            cities.Add("Mühlen");
            cities.Add("Murau");
            cities.Add("Mureck");
            cities.Add("Murfeld");
            cities.Add("Mürzzuschlag");
            cities.Add("Naas");
            cities.Add("Nestelbach bei Graz");
            cities.Add("Neuberg an der Mürz");
            cities.Add("Neudau");
            cities.Add("Neumarkt in der Steiermark");
            cities.Add("Niederwölz");
            cities.Add("Niklasdorf");
            cities.Add("Obdach");
            cities.Add("Oberhaag");
            cities.Add("Oberwölz");
            cities.Add("Öblarn");
            cities.Add("Ottendorf an der Rittschein");
            cities.Add("Paldau");
            cities.Add("Passail");
            cities.Add("Peggau");
            cities.Add("Pernegg an der Mur");
            cities.Add("Pinggau");
            cities.Add("Pirching am Traubenberg");
            cities.Add("Pischelsdorf am Kulm");
            cities.Add("Pölfing-Brunn");
            cities.Add("Pöllau");
            cities.Add("Pöllauberg");
            cities.Add("Pöls-Oberkurzheim");
            cities.Add("Pölstal");
            cities.Add("Preding");
            cities.Add("Premstätten");
            cities.Add("Proleb");
            cities.Add("Puch bei Weiz");
            cities.Add("Pusterwald");
            cities.Add("Raaba-Grambach");
            cities.Add("Radmer");
            cities.Add("Ragnitz");
            cities.Add("Ramsau am Dachstein");
            cities.Add("Ranten");
            cities.Add("Ratten");
            cities.Add("Rettenegg");
            cities.Add("Riegersburg");
            cities.Add("Rohr bei Hartberg");
            cities.Add("Rohrbach an der Lafnitz");
            cities.Add("Rosental an der Kainach");
            cities.Add("Rottenmann");
            cities.Add("Sankt Andrä-Höch");
            cities.Add("Sankt Anna am Aigen");
            cities.Add("Sankt Barbara im Mürztal");
            cities.Add("Sankt Bartholomä");
            cities.Add("Sankt Gallen");
            cities.Add("Sankt Georgen am Kreischberg");
            cities.Add("Sankt Georgen an der Stiefing");
            cities.Add("Sankt Georgen ob Judenburg");
            cities.Add("Sankt Jakob im Walde");
            cities.Add("Sankt Johann im Saggautal");
            cities.Add("Sankt Johann in der Haide");
            cities.Add("Sankt Josef");
            cities.Add("Sankt Kathrein am Offenegg");
            cities.Add("Sankt Lambrecht");
            cities.Add("Sankt Lorenzen am Wechsel");
            cities.Add("Sankt Lorenzen im Mürztal");
            cities.Add("Sankt Marein bei Graz");
            cities.Add("Sankt Marein im Mürztal");
            cities.Add("Sankt Marein-Feistritz");
            cities.Add("Sankt Margarethen bei Knittelfeld");
            cities.Add("Sankt Martin am Wöllmißberg");
            cities.Add("Sankt Martin im Sulmtal");
            cities.Add("Sankt Michael in Obersteiermark");
            cities.Add("Sankt Nikolai im Sausal");
            cities.Add("Sankt Oswald bei Plankenwarth");
            cities.Add("Sankt Peter am Ottersbach");
            cities.Add("Sankt Peter im Sulmtal");
            cities.Add("Sankt Peter ob Judenburg");
            cities.Add("Sankt Peter-Freienstein");
            cities.Add("Sankt Radegund bei Graz");
            cities.Add("Sankt Ruprecht an der Raab");
            cities.Add("Sankt Stefan im Rosental");
            cities.Add("Sankt Stefan ob Leoben");
            cities.Add("Sankt Stefan ob Stainz");
            cities.Add("Sankt Veit in der Südsteiermark");
            cities.Add("Schäffern");
            cities.Add("Scheifling");
            cities.Add("Schladming");
            cities.Add("Schöder");
            cities.Add("Schwanberg");
            cities.Add("Schwarzautal");
            cities.Add("Seckau");
            cities.Add("Seiersberg-Pirka");
            cities.Add("Selzthal");
            cities.Add("Semriach");
            cities.Add("Sinabelkirchen");
            cities.Add("Söchau");
            cities.Add("Söding-Sankt Johann");
            cities.Add("Sölk");
            cities.Add("Spielberg");
            cities.Add("Spital am Semmering");
            cities.Add("Sankt Kathrein am Hauenstein");
            cities.Add("Sankt Margarethen an der Raab");
            cities.Add("Sankt Peter am Kammersberg");
            cities.Add("Stadl-Predlitz");
            cities.Add("Stainach-Pürgg");
            cities.Add("Stainz");
            cities.Add("Stallhofen");
            cities.Add("Stanz im Mürztal");
            cities.Add("Stattegg");
            cities.Add("Stiwoll");
            cities.Add("Straden");
            cities.Add("Strallegg");
            cities.Add("Straß in Steiermark");
            cities.Add("Stubenberg");
            cities.Add("Teufenbach-Katsch");
            cities.Add("Thal");
            cities.Add("Thannhausen");
            cities.Add("Thörl");
            cities.Add("Tieschen");
            cities.Add("Tillmitsch");
            cities.Add("Traboch");
            cities.Add("Tragöß-Sankt Katharein");
            cities.Add("Trieben");
            cities.Add("Trofaiach");
            cities.Add("Turnau");
            cities.Add("Übelbach");
            cities.Add("Unterlamm");
            cities.Add("Unzmarkt-Frauenburg");
            cities.Add("Vasoldsberg");
            cities.Add("Voitsberg");
            cities.Add("Vorau");
            cities.Add("Vordernberg");
            cities.Add("Wagna");
            cities.Add("Wald am Schoberpaß");
            cities.Add("Waldbach-Mönichwald");
            cities.Add("Weinitzen");
            cities.Add("Weißkirchen in Steiermark");
            cities.Add("Weiz");
            cities.Add("Wenigzell");
            cities.Add("Werndorf");
            cities.Add("Wettmannstätten");
            cities.Add("Wies");
            cities.Add("Wildalpen");
            cities.Add("Wildon");
            cities.Add("Wörschach");
            cities.Add("Wundschuh");
            cities.Add("Zeltweg");
            cities.Add("Tyrol");
            cities.Add("Abfaltersbach");
            cities.Add("Absam");
            cities.Add("Achenkirch");
            cities.Add("Ainet");
            cities.Add("Aldrans");
            cities.Add("Alpbach");
            cities.Add("Amlach");
            cities.Add("Ampass");
            cities.Add("Angath");
            cities.Add("Angerberg");
            cities.Add("Anras");
            cities.Add("Arzl im Pitztal");
            cities.Add("Aschau im Zillertal");
            cities.Add("Assling");
            cities.Add("Aurach bei Kitzbühel");
            cities.Add("Außervillgraten");
            cities.Add("Axams");
            cities.Add("Bach");
            cities.Add("Bad Häring");
            cities.Add("Baumkirchen");
            cities.Add("Berwang");
            cities.Add("Biberwier");
            cities.Add("Bichlbach");
            cities.Add("Birgitz");
            cities.Add("Brandberg");
            cities.Add("Brandenberg");
            cities.Add("Breitenbach am Inn");
            cities.Add("Breitenwang");
            cities.Add("Brixen im Thale");
            cities.Add("Brixlegg");
            cities.Add("Bruck am Ziller");
            cities.Add("Buch in Tirol");
            cities.Add("Dölsach");
            cities.Add("Ebbs");
            cities.Add("Eben am Achensee");
            cities.Add("Ehenbichl");
            cities.Add("Ehrwald");
            cities.Add("Elbigenalp");
            cities.Add("Ellbögen");
            cities.Add("Ellmau");
            cities.Add("Elmen");
            cities.Add("Erl");
            cities.Add("Faggen");
            cities.Add("Fendels");
            cities.Add("Fieberbrunn");
            cities.Add("Finkenberg");
            cities.Add("Fiss");
            cities.Add("Flaurling");
            cities.Add("Fließ");
            cities.Add("Flirsch");
            cities.Add("Forchach");
            cities.Add("Fritzens");
            cities.Add("Fügen");
            cities.Add("Fügenberg");
            cities.Add("Fulpmes");
            cities.Add("Gaimberg");
            cities.Add("Gallzein");
            cities.Add("Galtür");
            cities.Add("Gerlos");
            cities.Add("Gerlosberg");
            cities.Add("Gnadenwald");
            cities.Add("Going am Wilden Kaiser");
            cities.Add("Götzens");
            cities.Add("Gramais");
            cities.Add("Grän");
            cities.Add("Gries am Brenner");
            cities.Add("Gries im Sellrain");
            cities.Add("Grins");
            cities.Add("Grinzens");
            cities.Add("Gschnitz");
            cities.Add("Haiming");
            cities.Add("Hainzenberg");
            cities.Add("Hall in Tirol");
            cities.Add("Hart im Zillertal");
            cities.Add("Häselgehr");
            cities.Add("Hatting");
            cities.Add("Heinfels");
            cities.Add("Heiterwang");
            cities.Add("Hinterhornbach");
            cities.Add("Hippach");
            cities.Add("Hochfilzen");
            cities.Add("Höfen");
            cities.Add("Holzgau");
            cities.Add("Hopfgarten im Brixental");
            cities.Add("Hopfgarten in Defereggen");
            cities.Add("Imst");
            cities.Add("Imsterberg");
            cities.Add("Innervillgraten");
            cities.Add("Innsbruck");
            cities.Add("Inzing");
            cities.Add("Ischgl");
            cities.Add("Iselsberg-Stronach");
            cities.Add("Itter");
            cities.Add("Jenbach");
            cities.Add("Jerzens");
            cities.Add("Jochberg");
            cities.Add("Jungholz");
            cities.Add("Kaisers");
            cities.Add("Kals am Großglockner");
            cities.Add("Kaltenbach");
            cities.Add("Kappl");
            cities.Add("Karres");
            cities.Add("Karrösten");
            cities.Add("Kartitsch");
            cities.Add("Kaunerberg");
            cities.Add("Kaunertal");
            cities.Add("Kauns");
            cities.Add("Kematen in Tirol");
            cities.Add("Kirchberg in Tirol");
            cities.Add("Kirchbichl");
            cities.Add("Kirchdorf in Tirol");
            cities.Add("Kitzbühel");
            cities.Add("Kolsass");
            cities.Add("Kolsassberg");
            cities.Add("Kössen");
            cities.Add("Kramsach");
            cities.Add("Kufstein");
            cities.Add("Kundl");
            cities.Add("Ladis");
            cities.Add("Landeck");
            cities.Add("Längenfeld");
            cities.Add("Langkampfen");
            cities.Add("Lans");
            cities.Add("Lavant");
            cities.Add("Lechaschau");
            cities.Add("Leisach");
            cities.Add("Lermoos");
            cities.Add("Leutasch");
            cities.Add("Lienz");
            cities.Add("Mariastein");
            cities.Add("Matrei am Brenner");
            cities.Add("Matrei in Osttirol");
            cities.Add("Mayrhofen");
            cities.Add("Mieders");
            cities.Add("Mieming");
            cities.Add("Mils");
            cities.Add("Mils bei Imst");
            cities.Add("Mötz");
            cities.Add("Mühlbachl");
            cities.Add("Münster");
            cities.Add("Musau");
            cities.Add("Mutters");
            cities.Add("Namlos");
            cities.Add("Nassereith");
            cities.Add("Natters");
            cities.Add("Nauders");
            cities.Add("Navis");
            cities.Add("Nesselwängle");
            cities.Add("Neustift im Stubaital");
            cities.Add("Niederndorf");
            cities.Add("Niederndorferberg");
            cities.Add("Nikolsdorf");
            cities.Add("Nußdorf-Debant");
            cities.Add("Oberhofen im Inntal");
            cities.Add("Oberlienz");
            cities.Add("Obernberg am Brenner");
            cities.Add("Oberndorf in Tirol");
            cities.Add("Oberperfuss");
            cities.Add("Obertilliach");
            cities.Add("Obsteig");
            cities.Add("Oetz");
            cities.Add("Patsch");
            cities.Add("Pettnau");
            cities.Add("Pettneu am Arlberg");
            cities.Add("Pfaffenhofen");
            cities.Add("Pfafflar");
            cities.Add("Pflach");
            cities.Add("Pfons");
            cities.Add("Pfunds");
            cities.Add("Pians");
            cities.Add("Pill");
            cities.Add("Pinswang");
            cities.Add("Polling in Tirol");
            cities.Add("Prägraten am Großvenediger");
            cities.Add("Prutz");
            cities.Add("Radfeld");
            cities.Add("Ramsau im Zillertal");
            cities.Add("Ranggen");
            cities.Add("Rattenberg");
            cities.Add("Reith bei Kitzbühel");
            cities.Add("Reith bei Seefeld");
            cities.Add("Reith im Alpbachtal");
            cities.Add("Rettenschöss");
            cities.Add("Reutte");
            cities.Add("Ried im Oberinntal");
            cities.Add("Ried im Zillertal");
            cities.Add("Rietz");
            cities.Add("Rinn");
            cities.Add("Rohrberg");
            cities.Add("Roppen");
            cities.Add("Rum");
            cities.Add("Sautens");
            cities.Add("Scharnitz");
            cities.Add("Schattwald");
            cities.Add("Scheffau am Wilden Kaiser");
            cities.Add("Schlaiten");
            cities.Add("Schlitters");
            cities.Add("Schmirn");
            cities.Add("Schönberg im Stubaital");
            cities.Add("Schönwies");
            cities.Add("Schwaz");
            cities.Add("Schwendau");
            cities.Add("Schwendt");
            cities.Add("Schwoich");
            cities.Add("See");
            cities.Add("Seefeld in Tirol");
            cities.Add("Sellrain");
            cities.Add("Serfaus");
            cities.Add("Sillian");
            cities.Add("Silz");
            cities.Add("Sistrans");
            cities.Add("Sölden");
            cities.Add("Söll");
            cities.Add("Spiss");
            cities.Add("St Anton am Arlberg");
            cities.Add("Sankt Jakob in Defereggen");
            cities.Add("Sankt Jakob in Haus");
            cities.Add("Sankt Johann im Walde");
            cities.Add("St. Johann in Tyrol");
            cities.Add("Sankt Leonhard im Pitztal");
            cities.Add("Sankt Sigmund im Sellrain");
            cities.Add("Sankt Ulrich am Pillersee");
            cities.Add("Sankt Veit in Defereggen");
            cities.Add("Stams");
            cities.Add("Stans");
            cities.Add("Stanz bei Landeck");
            cities.Add("Stanzach");
            cities.Add("Steeg");
            cities.Add("Steinach am Brenner");
            cities.Add("Steinberg am Rofan");
            cities.Add("Strass im Zillertal");
            cities.Add("Strassen");
            cities.Add("Strengen");
            cities.Add("Stumm");
            cities.Add("Stummerberg");
            cities.Add("Tannheim");
            cities.Add("Tarrenz");
            cities.Add("Telfes");
            cities.Add("Telfs");
            cities.Add("Terfens");
            cities.Add("Thaur");
            cities.Add("Thiersee");
            cities.Add("Thurn");
            cities.Add("Tobadill");
            cities.Add("Tösens");
            cities.Add("Trins");
            cities.Add("Tristach");
            cities.Add("Tulfes");
            cities.Add("Tux");
            cities.Add("Uderns");
            cities.Add("Umhausen");
            cities.Add("Unterperfuss");
            cities.Add("Untertilliach");
            cities.Add("Vals");
            cities.Add("Vils");
            cities.Add("Virgen");
            cities.Add("Volders");
            cities.Add("Völs");
            cities.Add("Vomp");
            cities.Add("Vorderhornbach");
            cities.Add("Waidring");
            cities.Add("Walchsee");
            cities.Add("Wängle");
            cities.Add("Wattenberg");
            cities.Add("Wattens");
            cities.Add("Weer");
            cities.Add("Weerberg");
            cities.Add("Weißenbach am Lech");
            cities.Add("Wenns");
            cities.Add("Westendorf");
            cities.Add("Wiesing");
            cities.Add("Wildermieming");
            cities.Add("Wildschönau");
            cities.Add("Wörgl");
            cities.Add("Zams");
            cities.Add("Zell am Ziller");
            cities.Add("Zellberg");
            cities.Add("Zirl");
            cities.Add("Zöblen");
            cities.Add("Adlwang");
            cities.Add("Afiesl");
            cities.Add("Ahorn");
            cities.Add("Aichkirchen");
            cities.Add("Aigen-Schlägl");
            cities.Add("Aistersheim");
            cities.Add("Alberndorf in der Riedmark");
            cities.Add("Alkoven");
            cities.Add("Allerheiligen im Mühlkreis");
            cities.Add("Allhaming");
            cities.Add("Altenberg bei Linz");
            cities.Add("Altenfelden");
            cities.Add("Altheim");
            cities.Add("Altmünster");
            cities.Add("Altschwendt");
            cities.Add("Ampflwang im Hausruckwald");
            cities.Add("Andorf");
            cities.Add("Andrichsfurt");
            cities.Add("Ansfelden");
            cities.Add("Antiesenhofen");
            cities.Add("Arbing");
            cities.Add("Arnreit");
            cities.Add("Aschach an der Donau");
            cities.Add("Aschach an der Steyr");
            cities.Add("Aspach");
            cities.Add("Asten");
            cities.Add("Attersee am Attersee");
            cities.Add("Attnang-Puchheim");
            cities.Add("Atzbach");
            cities.Add("Atzesberg");
            cities.Add("Auberg");
            cities.Add("Auerbach");
            cities.Add("Aurach am Hongar");
            cities.Add("Aurolzmünster");
            cities.Add("Bachmanning");
            cities.Add("Bad Goisern am Hallstättersee");
            cities.Add("Bad Hall");
            cities.Add("Bad Ischl");
            cities.Add("Bad Kreuzen");
            cities.Add("Bad Leonfelden");
            cities.Add("Bad Schallerbach");
            cities.Add("Bad Wimsbach-Neydharting");
            cities.Add("Bad Zell");
            cities.Add("Baumgartenberg");
            cities.Add("Berg im Attergau");
            cities.Add("Braunau am Inn");
            cities.Add("Brunnenthal");
            cities.Add("Buchkirchen");
            cities.Add("Burgkirchen");
            cities.Add("Desselbrunn");
            cities.Add("Diersbach");
            cities.Add("Dietach");
            cities.Add("Dimbach");
            cities.Add("Dorf an der Pram");
            cities.Add("Ebensee am Traunsee");
            cities.Add("Eberschwang");
            cities.Add("Eberstalzell");
            cities.Add("Edlbach");
            cities.Add("Edt bei Lambach");
            cities.Add("Eferding");
            cities.Add("Eggelsberg");
            cities.Add("Eggendorf im Traunkreis");
            cities.Add("Eggerding");
            cities.Add("Eidenberg");
            cities.Add("Eitzing");
            cities.Add("Engelhartszell an der Donau");
            cities.Add("Engerwitzdorf");
            cities.Add("Enns");
            cities.Add("Enzenkirchen");
            cities.Add("Eschenau im Hausruckkreis");
            cities.Add("Esternberg");
            cities.Add("Feldkirchen an der Donau");
            cities.Add("Feldkirchen bei Mattighofen");
            cities.Add("Fischlham");
            cities.Add("Fornach");
            cities.Add("Fraham");
            cities.Add("Frankenburg am Hausruck");
            cities.Add("Frankenmarkt");
            cities.Add("Franking");
            cities.Add("Freinberg");
            cities.Add("Freistadt");
            cities.Add("Gaflenz");
            cities.Add("Gallneukirchen");
            cities.Add("Gallspach");
            cities.Add("Gampern");
            cities.Add("Garsten");
            cities.Add("Gaspoltshofen");
            cities.Add("Geboltskirchen");
            cities.Add("Geiersberg");
            cities.Add("Geinberg");
            cities.Add("Geretsberg");
            cities.Add("Gilgenberg am Weilhart");
            cities.Add("Gmunden");
            cities.Add("Goldwörth");
            cities.Add("Gosau");
            cities.Add("Gramastetten");
            cities.Add("Grein");
            cities.Add("Grieskirchen");
            cities.Add("Großraming");
            cities.Add("Grünau im Almtal");
            cities.Add("Grünbach");
            cities.Add("Grünburg");
            cities.Add("Gschwandt");
            cities.Add("Gunskirchen");
            cities.Add("Gurten");
            cities.Add("Gutau");
            cities.Add("Haag am Hausruck");
            cities.Add("Hagenberg im Mühlkreis");
            cities.Add("Haibach im Mühlkreis");
            cities.Add("Haibach ob der Donau");
            cities.Add("Haigermoos");
            cities.Add("Hallstatt");
            cities.Add("Handenberg");
            cities.Add("Hargelsberg");
            cities.Add("Hartkirchen");
            cities.Add("Haslach an der Mühl");
            cities.Add("Heiligenberg");
            cities.Add("Helfenberg");
            cities.Add("Hellmonsödt");
            cities.Add("Helpfau-Uttendorf");
            cities.Add("Herzogsdorf");
            cities.Add("Hinterstoder");
            cities.Add("Hinzenbach");
            cities.Add("Hirschbach im Mühlkreis");
            cities.Add("Hochburg-Ach");
            cities.Add("Hofkirchen an der Trattnach");
            cities.Add("Hofkirchen im Mühlkreis");
            cities.Add("Hofkirchen im Traunkreis");
            cities.Add("Hohenzell");
            cities.Add("Höhnhart");
            cities.Add("Holzhausen");
            cities.Add("Hörbich");
            cities.Add("Hörsching");
            cities.Add("Innerschwand am Mondsee");
            cities.Add("Inzersdorf im Kremstal");
            cities.Add("Jeging");
            cities.Add("Julbach");
            cities.Add("Kallham");
            cities.Add("Kaltenberg");
            cities.Add("Katsdorf");
            cities.Add("Kefermarkt");
            cities.Add("Kematen am Innbach");
            cities.Add("Kematen an der Krems");
            cities.Add("Kirchberg bei Mattighofen");
            cities.Add("Kirchberg ob der Donau");
            cities.Add("Kirchberg-Thening");
            cities.Add("Kirchdorf am Inn");
            cities.Add("Kirchdorf an der Krems");
            cities.Add("Kirchham");
            cities.Add("Kirchheim im Innkreis");
            cities.Add("Kirchschlag bei Linz");
            cities.Add("Klaffer am Hochficht");
            cities.Add("Klam");
            cities.Add("Klaus an der Pyhrnbahn");
            cities.Add("Kleinzell im Mühlkreis");
            cities.Add("Kollerschlag");
            cities.Add("Königswiesen");
            cities.Add("Kopfing im Innkreis");
            cities.Add("Kremsmünster");
            cities.Add("Krenglbach");
            cities.Add("Kronstorf");
            cities.Add("Laakirchen");
            cities.Add("Lambach");
            cities.Add("Lambrechten");
            cities.Add("Langenstein");
            cities.Add("Lasberg");
            cities.Add("Laussa");
            cities.Add("Lembach im Mühlkreis");
            cities.Add("Lengau");
            cities.Add("Lenzing");
            cities.Add("Leonding");
            cities.Add("Leopoldschlag");
            cities.Add("Lichtenau im Mühlkreis");
            cities.Add("Lichtenberg");
            cities.Add("Liebenau");
            cities.Add("Linz");
            cities.Add("Lochen am See");
            cities.Add("Lohnsburg am Kobernaußerwald");
            cities.Add("Losenstein");
            cities.Add("Luftenberg an der Donau");
            cities.Add("Manning");
            cities.Add("Marchtrenk");
            cities.Add("Maria Neustift");
            cities.Add("Maria Schmolln");
            cities.Add("Mattighofen");
            cities.Add("Mauerkirchen");
            cities.Add("Mauthausen");
            cities.Add("Mayrhof");
            cities.Add("Meggenhofen");
            cities.Add("Mehrnbach");
            cities.Add("Mettmach");
            cities.Add("Michaelnbach");
            cities.Add("Micheldorf in Oberösterreich");
            cities.Add("Mining");
            cities.Add("Mitterkirchen im Machland");
            cities.Add("Molln");
            cities.Add("Mondsee");
            cities.Add("Moosbach");
            cities.Add("Moosdorf");
            cities.Add("Mörschwang");
            cities.Add("Mühlheim am Inn");
            cities.Add("Munderfing");
            cities.Add("Münzbach");
            cities.Add("Münzkirchen");
            cities.Add("Naarn im Machlande");
            cities.Add("Natternbach");
            cities.Add("Nebelberg");
            cities.Add("Neufelden");
            cities.Add("Neuhofen an der Krems");
            cities.Add("Neuhofen im Innkreis");
            cities.Add("Neukirchen am Walde");
            cities.Add("Neukirchen an der Enknach");
            cities.Add("Neukirchen an der Vöckla");
            cities.Add("Neukirchen bei Lambach");
            cities.Add("Neumarkt im Hausruckkreis");
            cities.Add("Neumarkt im Mühlkreis");
            cities.Add("Neustift im Mühlkreis");
            cities.Add("Niederkappel");
            cities.Add("Niederneukirchen");
            cities.Add("Niederthalheim");
            cities.Add("Niederwaldkirchen");
            cities.Add("Nußbach");
            cities.Add("Nußdorf am Attersee");
            cities.Add("Oberhofen am Irrsee");
            cities.Add("Oberkappel");
            cities.Add("Obernberg am Inn");
            cities.Add("Oberndorf bei Schwanenstadt");
            cities.Add("Oberneukirchen");
            cities.Add("Oberschlierbach");
            cities.Add("Obertraun");
            cities.Add("Oberwang");
            cities.Add("Oepping");
            cities.Add("Offenhausen");
            cities.Add("Oftering");
            cities.Add("Ohlsdorf");
            cities.Add("Ort im Innkreis");
            cities.Add("Ostermiething");
            cities.Add("Ottenschlag im Mühlkreis");
            cities.Add("Ottensheim");
            cities.Add("Ottnang am Hausruck");
            cities.Add("Pabneukirchen");
            cities.Add("Palting");
            cities.Add("Pasching");
            cities.Add("Pattigham");
            cities.Add("Peilstein im Mühlviertel");
            cities.Add("Pennewang");
            cities.Add("Perg");
            cities.Add("Perwang am Grabensee");
            cities.Add("Peterskirchen");
            cities.Add("Pettenbach");
            cities.Add("Peuerbach");
            cities.Add("Pfaffing");
            cities.Add("Pfaffstätt");
            cities.Add("Pfarrkirchen bei Bad Hall");
            cities.Add("Pfarrkirchen im Mühlkreis");
            cities.Add("Piberbach");
            cities.Add("Pichl bei Wels");
            cities.Add("Pierbach");
            cities.Add("Pilsbach");
            cities.Add("Pinsdorf");
            cities.Add("Pischelsdorf am Engelbach");
            cities.Add("Pitzenberg");
            cities.Add("Pollham");
            cities.Add("Polling im Innkreis");
            cities.Add("Pöndorf");
            cities.Add("Pötting");
            cities.Add("Pram");
            cities.Add("Prambachkirchen");
            cities.Add("Pramet");
            cities.Add("Pregarten");
            cities.Add("Puchenau");
            cities.Add("Puchkirchen am Trattberg");
            cities.Add("Pucking");
            cities.Add("Pühret");
            cities.Add("Pupping");
            cities.Add("Putzleinsdorf");
            cities.Add("Raab");
            cities.Add("Rainbach im Innkreis");
            cities.Add("Rainbach im Mühlkreis");
            cities.Add("Rechberg");
            cities.Add("Redleiten");
            cities.Add("Redlham");
            cities.Add("Regau");
            cities.Add("Reichenau im Mühlkreis");
            cities.Add("Reichenthal");
            cities.Add("Reichersberg");
            cities.Add("Reichraming");
            cities.Add("Ried im Innkreis");
            cities.Add("Ried im Traunkreis");
            cities.Add("Ried in der Riedmark");
            cities.Add("Riedau");
            cities.Add("Rohr im Kremstal");
            cities.Add("Rohrbach-Berg");
            cities.Add("Roitham am Traunfall");
            cities.Add("Rosenau am Hengstpaß");
            cities.Add("Roßbach");
            cities.Add("Roßleithen");
            cities.Add("Rottenbach");
            cities.Add("Rüstorf");
            cities.Add("Rutzenham");
            cities.Add("Sandl");
            cities.Add("Sarleinsbach");
            cities.Add("Sattledt");
            cities.Add("Saxen");
            cities.Add("Schalchen");
            cities.Add("Schardenberg");
            cities.Add("Schärding");
            cities.Add("Scharnstein");
            cities.Add("Scharten");
            cities.Add("Schenkenfelden");
            cities.Add("Schiedlberg");
            cities.Add("Schildorn");
            cities.Add("Schlatt");
            cities.Add("Schleißheim");
            cities.Add("Schlierbach");
            cities.Add("Schlüßlberg");
            cities.Add("Schönau im Mühlkreis");
            cities.Add("Schörfling am Attersee");
            cities.Add("Schwand im Innkreis");
            cities.Add("Schwanenstadt");
            cities.Add("Schwarzenberg am Böhmerwald");
            cities.Add("Schwertberg");
            cities.Add("Seewalchen am Attersee");
            cities.Add("Senftenbach");
            cities.Add("Sierning");
            cities.Add("Sigharting");
            cities.Add("Sipbachzell");
            cities.Add("Sonnberg im Mühlkreis");
            cities.Add("Spital am Pyhrn");
            cities.Add("Sankt Aegidi");
            cities.Add("Sankt Agatha");
            cities.Add("Sankt Florian");
            cities.Add("Sankt Florian am Inn");
            cities.Add("Sankt Georgen am Fillmannsbach");
            cities.Add("Sankt Georgen am Walde");
            cities.Add("Sankt Georgen an der Gusen");
            cities.Add("Sankt Georgen bei Grieskirchen");
            cities.Add("Sankt Georgen bei Obernberg am Inn");
            cities.Add("St Georgen im Attergau");
            cities.Add("Sankt Gotthard im Mühlkreis");
            cities.Add("Sankt Johann am Walde");
            cities.Add("Sankt Johann am Wimberg");
            cities.Add("Sankt Konrad");
            cities.Add("Sankt Leonhard bei Freistadt");
            cities.Add("Sankt Lorenz");
            cities.Add("Sankt Marien");
            cities.Add("St. Marienkirchen am Hausruck");
            cities.Add("Sankt Marienkirchen an der Polsenz");
            cities.Add("Sankt Marienkirchen bei Schärding");
            cities.Add("Sankt Martin im Innkreis");
            cities.Add("Sankt Martin im Mühlkreis");
            cities.Add("Sankt Nikola an der Donau");
            cities.Add("Sankt Oswald bei Freistadt");
            cities.Add("Sankt Oswald bei Haslach");
            cities.Add("Sankt Pankraz");
            cities.Add("Sankt Pantaleon");
            cities.Add("Sankt Peter am Hart");
            cities.Add("Sankt Peter am Wimberg");
            cities.Add("St. Radegund");
            cities.Add("Sankt Roman");
            cities.Add("Sankt Stefan am Walde");
            cities.Add("Sankt Thomas");
            cities.Add("Sankt Thomas am Blasenstein");
            cities.Add("Sankt Ulrich bei Steyr");
            cities.Add("Sankt Ulrich im Mühlkreis");
            cities.Add("Sankt Veit im Innkreis");
            cities.Add("Sankt Veit im Mühlkreis");
            cities.Add("Sankt Willibald");
            cities.Add("St. Wolfgang im Salzkammergut");
            cities.Add("Stadl-Paura");
            cities.Add("Steegen");
            cities.Add("Steinbach am Attersee");
            cities.Add("Steinbach am Ziehberg");
            cities.Add("Steinbach an der Steyr");
            cities.Add("Steinerkirchen an der Traun");
            cities.Add("Steinhaus");
            cities.Add("Steyr");
            cities.Add("Steyregg");
            cities.Add("Straß im Attergau");
            cities.Add("Stroheim");
            cities.Add("Suben");
            cities.Add("Taiskirchen im Innkreis");
            cities.Add("Tarsdorf");
            cities.Add("Taufkirchen an der Pram");
            cities.Add("Taufkirchen an der Trattnach");
            cities.Add("Ternberg");
            cities.Add("Thalheim bei Wels");
            cities.Add("Tiefgraben");
            cities.Add("Timelkam");
            cities.Add("Tollet");
            cities.Add("Tragwein");
            cities.Add("Traun");
            cities.Add("Traunkirchen");
            cities.Add("Treubach");
            cities.Add("Tumeltsham");
            cities.Add("Überackern");
            cities.Add("Ulrichsberg");
            cities.Add("Ungenach");
            cities.Add("Unterach am Attersee");
            cities.Add("Unterweißenbach");
            cities.Add("Unterweitersdorf");
            cities.Add("Utzenaich");
            cities.Add("Vichtenstein");
            cities.Add("Vöcklabruck");
            cities.Add("Vöcklamarkt");
            cities.Add("Vorchdorf");
            cities.Add("Vorderstoder");
            cities.Add("Vorderweißenbach");
            cities.Add("Waizenkirchen");
            cities.Add("Waldburg");
            cities.Add("Waldhausen im Strudengau");
            cities.Add("Walding");
            cities.Add("Waldkirchen am Wesen");
            cities.Add("Waldneukirchen");
            cities.Add("Waldzell");
            cities.Add("Wallern an der Trattnach");
            cities.Add("Wartberg an der Krems");
            cities.Add("Wartberg ob der Aist");
            cities.Add("Weibern");
            cities.Add("Weilbach");
            cities.Add("Weißenkirchen im Attergau");
            cities.Add("Weißkirchen an der Traun");
            cities.Add("Weitersfelden");
            cities.Add("Wels");
            cities.Add("Wendling");
            cities.Add("Weng im Innkreis");
            cities.Add("Wernstein am Inn");
            cities.Add("Weyer");
            cities.Add("Weyregg am Attersee");
            cities.Add("Wilhering");
            cities.Add("Windhaag bei Freistadt");
            cities.Add("Windhaag bei Perg");
            cities.Add("Windischgarsten");
            cities.Add("Wippenham");
            cities.Add("Wolfern");
            cities.Add("Wolfsegg am Hausruck");
            cities.Add("Zell am Moos");
            cities.Add("Zell am Pettenfirst");
            cities.Add("Zell an der Pram");
            cities.Add("Zwettl an der Rodl");
            cities.Add("Vienna");
            cities.Add("Alberschwende");
            cities.Add("Altach");
            cities.Add("Andelsbuch");
            cities.Add("Au");
            cities.Add("Bartholomäberg");
            cities.Add("Bezau");
            cities.Add("Bildstein");
            cities.Add("Bizau");
            cities.Add("Blons");
            cities.Add("Bludenz");
            cities.Add("Bludesch");
            cities.Add("Brand");
            cities.Add("Bregenz");
            cities.Add("Buch");
            cities.Add("Bürs");
            cities.Add("Bürserberg");
            cities.Add("Dalaas");
            cities.Add("Damüls");
            cities.Add("Doren");
            cities.Add("Dornbirn");
            cities.Add("Düns");
            cities.Add("Dünserberg");
            cities.Add("Egg");
            cities.Add("Eichenberg");
            cities.Add("Feldkirch");
            cities.Add("Fontanella");
            cities.Add("Frastanz");
            cities.Add("Fraxern");
            cities.Add("Fußach");
            cities.Add("Gaißau");
            cities.Add("Gemeinde Gaschurn-Partenen");
            cities.Add("Göfis");
            cities.Add("Götzis");
            cities.Add("Hard");
            cities.Add("Hittisau");
            cities.Add("Höchst");
            cities.Add("Hohenems");
            cities.Add("Hohenweiler");
            cities.Add("Hörbranz");
            cities.Add("Innerbraz");
            cities.Add("Kennelbach");
            cities.Add("Klaus");
            cities.Add("Klösterle");
            cities.Add("Koblach");
            cities.Add("Krumbach");
            cities.Add("Langen bei Bregenz");
            cities.Add("Langenegg");
            cities.Add("Laterns");
            cities.Add("Lauterach");
            cities.Add("Lech");
            cities.Add("Lingenau");
            cities.Add("Lochau");
            cities.Add("Lorüns");
            cities.Add("Ludesch");
            cities.Add("Lustenau");
            cities.Add("Mäder");
            cities.Add("Meiningen");
            cities.Add("Mellau");
            cities.Add("Mittelberg");
            cities.Add("Möggers");
            cities.Add("Nenzing");
            cities.Add("Nüziders");
            cities.Add("Raggal");
            cities.Add("Rankweil");
            cities.Add("Reuthe");
            cities.Add("Riefensberg");
            cities.Add("Röns");
            cities.Add("Röthis");
            cities.Add("Satteins");
            cities.Add("Schlins");
            cities.Add("Schnepfau");
            cities.Add("Schnifis");
            cities.Add("Schoppernau");
            cities.Add("Schröcken");
            cities.Add("Schruns");
            cities.Add("Schwarzach");
            cities.Add("Schwarzenberg");
            cities.Add("Sibratsgfäll");
            cities.Add("Silbertal");
            cities.Add("Sonntag");
            cities.Add("Sankt Anton im Montafon");
            cities.Add("St. Gallenkirch");
            cities.Add("Sankt Gerold");
            cities.Add("Stallehr");
            cities.Add("Sulz");
            cities.Add("Sulzberg");
            cities.Add("Thüringen");
            cities.Add("Thüringerberg");
            cities.Add("Tschagguns");
            cities.Add("Übersaxen");
            cities.Add("Vandans");
            cities.Add("Viktorsberg");
            cities.Add("Warth");
            cities.Add("Weiler");
            cities.Add("Wolfurt");
            cities.Add("Zwischenwasser");
        }

        [HttpGet("Lookup")]
        public IEnumerable<string> Lookup(string searchTerm)
        {
            string[] result = cities
                .Where(c => c.StartsWith(searchTerm, StringComparison.InvariantCultureIgnoreCase))
                .ToArray();

            return result;
        }
    }
}